DS Group 0.1rc1
smal1378/Bank-3992 pull request #12
Opened 2021-05-30 00:00 UTC by MASaraji

2021-05-30 01:36 UTC, farooqkz commented
Fix the following problems:
 - https://github.com/MASaraji/Bank-3992/blob/master/DSModels.py#L92 Use dictionaries
 - https://github.com/MASaraji/Bank-3992/blob/master/DS.py#L10 Use Enum
 - https://github.com/MASaraji/Bank-3992/blob/master/DS.py#L197 Maybe use `default` argument of `get` method?

2021-05-30 21:27 UTC, smal1378 requested changes

2021-05-30 21:27 UTC, smal1378 commented on DS.py
>      def change_username(self, old_username, new_username, types):
دقت کنید، این متد و متد بعدی اصلا در فایل لیست متدها نیستند.

2021-05-30 21:27 UTC, smal1378 commented on DSModels.py
> +        sleep(.00001)
دقیقا هدف از این چیست؟

2021-05-30 21:27 UTC, smal1378 commented on DSModels.py
> +        sleep(.00001)
و همچنین هدف این خط کد

2021-05-30 21:31 UTC, MASaraji commented on DS.py
>      def change_username(self, old_username, new_username, types):
درسته نیستم چون تغییر رمز و یوزرنیم یه دنیای دیگه ست با تغییر بقیه چیز ها فرق داره

2021-05-30 21:32 UTC, MASaraji commented on DSModels.py
> +        sleep(.00001)
اگه منظورت sleep هستش که توی گروه گفتم بعضی مواقع زمان دقیقا منطبق میشه و توی دیکشنری جایگزین میشه

2021-05-30 21:33 UTC, MASaraji commented on DSModels.py
> +        sleep(.00001)
با بالایی به هدف رو دنبال میکنن

2021-06-02 16:03 UTC, smal1378 commented
فایل هایی که توی پوشه داکس هستن داستانش چیه؟
 بیزحمت برای اینکه پروژه شلوغ نشه حذفش کنید

2021-06-02 22:05 UTC, merged